---
:development: &defaults
  :adapter: sqlite3
  :database: db/development.sqlite3.db

:test:
  <<: *defaults
  :database: db/test.sqlite3.db

:production:
  <<: *defaults
  :apapter: mysql
  :database: db/production.sqlite3.db
  :username:
  :password:
  :host: localhost
  :socket:
