---
:development: &defaults
  :adapter: sqlite3
  :database: db/development.sqlite3.db

:test:
  <<: *defaults
  :database: db/test.sqlite3.db

:production:
  :adapter: mysql
  :database: tlm_tweetlinkmonster
  :username: tlm_tlm
  :password: guessy3cant!
  :host: localhost
